# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ScheduleOption(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, schedule_id: int=None, nuid: int=None, semester: str=None, year: int=None):  # noqa: E501
        """ScheduleOption - a model defined in Swagger

        :param schedule_id: The schedule_id of this ScheduleOption.  # noqa: E501
        :type schedule_id: int
        :param nuid: The nuid of this ScheduleOption.  # noqa: E501
        :type nuid: int
        :param semester: The semester of this ScheduleOption.  # noqa: E501
        :type semester: str
        :param year: The year of this ScheduleOption.  # noqa: E501
        :type year: int
        """
        self.swagger_types = {
            'schedule_id': int,
            'nuid': int,
            'semester': str,
            'year': int
        }

        self.attribute_map = {
            'schedule_id': 'schedule_id',
            'nuid': 'nuid',
            'semester': 'semester',
            'year': 'year'
        }

        self._schedule_id = schedule_id
        self._nuid = nuid
        self._semester = semester
        self._year = year

    @classmethod
    def from_dict(cls, dikt) -> 'ScheduleOption':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScheduleOption of this ScheduleOption.  # noqa: E501
        :rtype: ScheduleOption
        """
        return util.deserialize_model(dikt, cls)

    @property
    def schedule_id(self) -> int:
        """Gets the schedule_id of this ScheduleOption.


        :return: The schedule_id of this ScheduleOption.
        :rtype: int
        """
        return self._schedule_id

    @schedule_id.setter
    def schedule_id(self, schedule_id: int):
        """Sets the schedule_id of this ScheduleOption.


        :param schedule_id: The schedule_id of this ScheduleOption.
        :type schedule_id: int
        """

        self._schedule_id = schedule_id

    @property
    def nuid(self) -> int:
        """Gets the nuid of this ScheduleOption.


        :return: The nuid of this ScheduleOption.
        :rtype: int
        """
        return self._nuid

    @nuid.setter
    def nuid(self, nuid: int):
        """Sets the nuid of this ScheduleOption.


        :param nuid: The nuid of this ScheduleOption.
        :type nuid: int
        """

        self._nuid = nuid

    @property
    def semester(self) -> str:
        """Gets the semester of this ScheduleOption.

        a semester offered during a year  # noqa: E501

        :return: The semester of this ScheduleOption.
        :rtype: str
        """
        return self._semester

    @semester.setter
    def semester(self, semester: str):
        """Sets the semester of this ScheduleOption.

        a semester offered during a year  # noqa: E501

        :param semester: The semester of this ScheduleOption.
        :type semester: str
        """
        allowed_values = ["fall", "spring", "summer 1", "summer 2", "full summer"]  # noqa: E501
        if semester not in allowed_values:
            raise ValueError(
                "Invalid value for `semester` ({0}), must be one of {1}"
                .format(semester, allowed_values)
            )

        self._semester = semester

    @property
    def year(self) -> int:
        """Gets the year of this ScheduleOption.


        :return: The year of this ScheduleOption.
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year: int):
        """Sets the year of this ScheduleOption.


        :param year: The year of this ScheduleOption.
        :type year: int
        """
        if year is not None and year > 3000:  # noqa: E501
            raise ValueError("Invalid value for `year`, must be a value less than or equal to `3000`")  # noqa: E501
        if year is not None and year < 2000:  # noqa: E501
            raise ValueError("Invalid value for `year`, must be a value greater than or equal to `2000`")  # noqa: E501

        self._year = year
